language: python
python:
- '3.7'
install:
- pip install -e .
- cd develop
- python manage.py migrate
script:
- python manage.py test permafrost
- cd ..
deploy:
  provider: pypi
  user: __token__
  password:
    secure: EmG+o+ZwL1t7wFwTRPgFkVJwxuTEeOe70AyufA/VklvC/iSYlO+m68XFdurgZ7UHK7Bg5ZvuMFu7IVOVz1GTB36WRaDoXdkVlgPR79mk/ycVrwA64vbFrxkfXYOUllm5GnkVDSZ+ryueS0MjnufE27lP1BLzszxAZAh8ok+pXQGE+5JLR/hOWVodGHY9djMh/yscDMU5S3nwPbHTvyYTIU/ioCXdKlIwmuDrUupJsXKoYe1ZsJ/YtvPXZgZaGAUEoJW6sUdFZ4Ci609YnbOPduJcLeq9GLzo+VuZEUPWd3Rl+rG6sYy6qbVyQfTz8xKzT22HwM69bwWGFFke2W1plULs9GiLYGg3pmZr9eAaVKN8X053s/tY17o8x1R/OKE497tPsiaqViUeVF8sN+57kaWHRHIEkFPSMxc6m3TUrZVlDwdOF9NQxM0aWQfqZ/9YKCM1vPxqi87FkozoJJxc/PcHSLT9LsIHh58D7AgAtgm/DGp4awzUWU7QsQi6i/a4fPRAB43+4nMZETus3RdLT4xM36jG1FV0P59iJ8eOaPd1vrBWtDVGXDM0w1y8/kY9qmxW6kJmcFVqc9w2ePXkwVK6o4qPNHEPwqTAM3/uW+YXBELBXeBem0ID6v12uQJgDbJtB+NEfJEUkptos+JGrGYLua4Jtb9CfPa91T6nHBk=
